### ISSUE TITLE
[License] Consider change license to MIT license

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#127]
Some developer don't like GPL license, and their project source code is not very useful to me, so I will consider change license to MIT in 1.0.0 stable version.

**Comment by Raymonf** [comment]
Yes, please!

This project looks really cool but I don't really want to touch GPLv2 code because of the source code clause.

**Comment by mqudsi** [comment]
Thank you. Libraries really should always use MIT/BSD/LGPL to boost adoption.

**Comment by aggsol** [comment]
I vote for sticking to GPL even though their code is not useful to you it might be useful to somebody else using LCUI. Also the GPL is not for "usefulness" but to share knowledge. With LGPL you give people and companies to rely on LCUI and create commercial products without giving back.

Please have a read from GNU on why *not* to use LGPL on new libraries.

https://www.gnu.org/licenses/why-not-lgpl.en.html

Thank you for your great work!

**Comment by baybal** [comment]
Consider v3 or v3l

Then, you can use code from qt and gtk

**Comment by baybal** [comment]
Other than for projects that are too big to change license V2 codebase is pretty much dead

**Comment by codecat** [comment]
Ah damn. I wanted to use this but didn't realize it was GPL'd. Would much prefer an MIT license!

**Comment by Raymonf** [comment]
@aggsol I understand where you're coming from, but in that case most people will just not use the library. That group includes me.

We're totally fine with not using this, but we'd love to. That's all.

**Comment by lieff** [comment]
+1 for more permissive license.

**Comment by lc-soft** [comment]
@aggsol 

Yes, I think so before open this project source, I just hope someone can tell me how to write code and make this project better. But what I can not understand is that with so many GUI libraries, why use this project?

Many people are selfish, do not want to open source their own projects, do not like the GPL license, So the GPL library will not be formally used in their own projects, which also led to a chain reaction: 

1. nobody used this project
1. nobody found this project bugs
1. nobody study source code to fix bug
1. nobody share this bug's patch
1. This project will not be developed speed

So, I think the switch to LGPL license might solve the problem.

But if I switch to another license, may be will bring more users, these users will bring more needs, and my free time is limited, I will certainly not totally agree with their needs, I guess some bad attitude users are dissatisfied, and then do some unpleasant things, just as [this developer's article said](https://snarky.ca/why-i-took-october-off-from-oss-volunteering/?utm_source=wanqu.co&utm_campaign=Wanqu%20Daily&utm_medium=website).
Think carefully, use what license has little effect on me, the number of users and the number of stars is just a number, the benefits they bring to me are just making it easier for me to find new jobs.

**Comment by Raymonf** [comment]
That being said...

@lc-soft Is [lc-ui/LCUI-Guide](https://github.com/lc-ui/LCUI-Guide) up to date? I'd like to translate it since we're missing an English version.

**Comment by baybal** [comment]
@lc-soft the bigger issue is the version. You can't use (L)GPL V2 code in a (L)GPL V3 project, and vice versa. And GPL V2 codebase is getting vanishingly small these days with exception of projects that stuck with V2 because of their size.

So, even if I will release my software under the same license as LCUI, I will not be able to use any of popular third party libraries, and that is a showstopper.

**Comment by aggsol** [comment]
In this cas LGPL might be a good choice for @lc-soft . 

@baybal  If you just link to LCUI what most people will do you can use ANY compatible license for your project. If v2 or v2 is no matter then.

**Comment by baybal** [comment]
@aggsol what you are saying is wrong. Linking to a library invariably creates a derived work as per GPL's language. That way your binary turns into GPLV2 code which can't use v3 libs

**Comment by codecat** [comment]
@baybal What about with LGPL though?

**Comment by baybal** [comment]
@codecat LGPL allows linking without relicensing of a derived work.

> You may convey a Combined Work under terms of your choice that, taken together, effectively do not restrict modification of the portions of the Library contained in the Combined Work and reverse engineering for debugging such modifications

**Comment by aggsol** [comment]
@baybal Yes, I was talking about LGPL. Just to be clear. I hind sight LGPL might a good choice after all in this case.

**Comment by ForsakenHarmony** [comment]
Just use MIT and be done with it

**Comment by lc-soft** [comment]
> Is lc-ui/LCUI-Guide up to date? I'd like to translate it since we're missing an English version.

@Raymonf 

No, I have plans to rewrite some chapters, only one hello world demo code in this tutorial may not be enough, you can recommend some examples, like: news list, login panel, etc.

But these may take a long time, because now I need to develop [LCUI.css](https://github.com/lc-ui/lcui.css) 0.1 version.

**Comment by herrbischoff** [comment]
It’s pretty simple really. Just look at the discussion here and you’ll realize what a mess GPL licenses are. No one *truly* knows what its effects are, not even the FSF who created it. This creates ambiguity and leads to people not using your library.

If you don’t want to support it because your time is limited, well, then don’t. All the more reason to liberally license the code so people can take it and do anything they want with it. Trying to force people to open source their code has never worked in my experience. They just move on to the next thing. Same reason the Nintendo Switch, PS4 and many other devices of quality are based on FreeBSD rather than Linux: the license. Well, that and the fact it’s a full operating system, not just a collection of a kernel and packages. But mainly because of the license. And yes, those companies do give back because it’s in their own economic interest to have the core features they care about supported and checked for issues – with no cost to them.

It comes down to an ideological choice: do you want to see the broadest possible usage of your library because you’re invested in free and open software or are you really just sharing code to show off your skills in hopes of attracting business?

**Comment by sam0x17** [comment]
These days I don't really understand why any open source project wouldn't use the MIT license unless they intend to make money off of restricting/licensing the code in some way. LGPL is a step in the right direction, but MIT would be even less onerous.

**Comment by codecat** [comment]
I typically pick MIT for libraries (so that they're actually useful in closed-source projects) and GPL for programs (because why would anyone want to use that code in closed-source?)

**Comment by lc-soft** [comment]
OK, I can consider choosing the MIT license to reduce your constraints, and it can reduce my stress. Becuase this is a personal project, did not like Qt have a company to maintain it and have time to provide technical services to users of commercial license. Rely on the use of LGPL license and commercial license mode to obtain financial income is unrealistic.

but the development of this project is slow, I hope you do not complain.

**Comment by baybal** [comment]
The flaws of "freeloader licensing" like mit, 2c BSD, APL and on are that nobody is being _forced_ by the contract to contribute back.

This is important because there are no decent free native GUI toolkits. For as long as there are no alternatives to GTK or Qt, freeloading devs are being limited to using something like Electron. Their either have to open their code or not being able to sell their stuff. Very simple.

The best proof for that the fact that _out of all_ free gui toolkits released over last 3 decades, only genuine opensource projects - Qt and GTK lasted to this day, and all others turned abandonware as soon as their sponsors' interest faded.

LCUI might not be a big project now, but it has all chances to become one one. Qt and GTK do have problems with being to huge. LCUI as it is now, has appeal for being small, GL oriented, and not having huge dependency trail.

**Comment by lc-soft** [comment]
So, what tool can replace header license text in all source files? manual replacement is very troublesome.

**Comment by codecat** [comment]
@baybal [WxWidgets](https://github.com/wxWidgets/wxWidgets) is still maintained, though.

@lc-soft It's probably possible to do a search & replace in any IDE, I would imagine.

**Comment by baybal** [comment]
@codecat WxWidgets is just a thin layer on top of gtk+/cocoa/gdi+. it does not do much drawing by itself.

**Comment by codecat** [comment]
@baybal Oh for sure, but it's still a UI framework. It's not hardware accelerated or highly customizable in terms of its looks, but it's still a framework. :D

**Comment by herrbischoff** [comment]
> but the development of this project is slow, I hope you do not complain.

Not at all. I for one am actually happy it exists at all and you now chose a liberal license based on the feedback here. I'm confident it will positively influence adaption and hopefully contribution.

**Comment by technosaurus** [comment]
I had completely written this project off due to the license and couldn't for the life of me figure out why it started trending.  Now I understand; and  can  stop messing with tekui (a similar permissibly licensed project written in c and lua)

Thanks.
