### ISSUE TITLE
Question : Support MacOs?

### ISSUE THREAD

**Issue by QuestionPython** [lc-soft/LCUI#155]
Question : What means `Cross Platform` there?
https://github.com/lc-soft/LCUI/blob/develop/README.md

Only **Windows , Linux , MacOs** ?

is better then change `README` file.

look at https://github.com/lc-soft/LCUI/tree/develop/src/platform
there are only linux and windows.
so why you are display **Cross Platform** at ReadME when not support MacOs and more...?

**Comment by lc-soft** [comment]
Q: Only Windows , Linux , MacOs ?

A: Only **Windows** an **Linux**. The cross-platform I understand means that at least two platforms are supported.

Q: there are only linux and windows. so why you are display Cross Platform at ReadME when not support MacOs and more...?

A: Yes. But you can try to build it under Mac OS. Because the support code for the Linux platform is based on the [x11](https://en.wikipedia.org/wiki/X_Window_System), it does not call Linux-specific APIs. I don't have a MacOS and I can't verify if I can build it. These are just my guesses.

**Comment by ilearnio** [comment]
On mac when I did `./configure` step, it got this
```
-e Build with lcui-builder support .... : yes
-e Build with libpng support .......... : yes
-e Build with libjpeg support ......... : yes
-e Build with font-engine support ..... : none
-e Build with fontconfig support ...... : yes
-e Build with thread support .......... : pthread
-e Build with video support ........... : none
```

So I guess font and video support is missing for some reason. It doesn't show what is the problem.

Then it fails at `make` step.

```
...
  CC       linux/linux_display.lo
  CC       linux/linux_mouse.lo
linux/linux_mouse.c:41:10: fatal error: 'linux/input.h' file not found
#include <linux/input.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [linux/linux_mouse.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by lc-soft** [comment]
@ilearnio 

The `<linux/input.h>` are not used in linux_mouse.c, I made some changes, Please pull the `develop` branch and try to rebuild.

For the video support, you can use "[compile x11 program in Mac](https://www.google.com/search?q=compile+x11+program+in+Mac)" to search for relevant content, like this:

https://stackoverflow.com/questions/14321038/x11-xlib-h-no-such-file-or-directory-on-mac-os-x-mountain-lion
