### ISSUE TITLE
Porting the "drawing core"

### ISSUE THREAD

**Issue by nomi-san** [lc-soft/LCUI#226]
Hi,

It's known that the "**LCUI's drawing core**" is based on PNG image and doesn't support hardware acceleration, but I'm interested in this awesome.
Is it possible to port as an independent library? And how if possible? 😀

Thanks.

**Comment by lc-soft** [comment]
> Is it possible to port as an independent library? 

Yes, but some modifications are required. I had this idea a long time ago, but I didn’t have time to do it, and I don’t know much about other graphics libraries to design the best and easy-to-use graphics API.

>  And how if possible? 

The following steps are required:

1. Refer to the design of other graphics libraries and design a series of easy-to-use graphics APIs for the new graphics library.
2. Write code to implement the functions of these APIs.
3. Write Makefile or CMake configuration file.
4. Submit portfiles to [vcpkg](https://github.com/microsoft/vcpkg) so that other developers can install it using vcpkg.

**Comment by nomi-san** [comment]
Thanks, but.. I mean how to reuse "**LCUI's drawing core**", for drawing something without the GUI.

**Comment by lc-soft** [comment]
> I mean how to reuse "LCUI's drawing core", for drawing something without the GUI.

@nomi-san 

Do you want me to provide sample code to show how to call the graphics API to drawing something without the GUI, or do you want me to change the drawing core to a library that can be used independently? If it is the former, I will consider it when I have time. If it is the latter, it is temporarily impossible.

**Comment by nomi-san** [comment]
Yep,
> provide sample code to show how to call the graphics API...

// If you don't have time, I'll do the research myself 😅
