### ISSUE TITLE
File Dialog?

### ISSUE THREAD

**Issue by wagb283** [lc-soft/LCUI#290]
Chao, is there any plan for a file dialog? This is a very promising project, I hope you will continue with development.

**Comment by lc-soft** [comment]
You mean the file selection dialog? Like this: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog?view=windowsdesktop-6.0

In another project, I called the function provided by the system to display the file dialog. You can find the relevant code in this file: https://github.com/lc-soft/LC-Finder/blob/develop/src/bridge_win32.cpp

If you need a file dialog based on the LCUI implementation, it may take a long time, because I am currently developing version 3.0.
